# This config file focuses on hotkeys, winrules, autostart, etc.

# Auto-run
exec-once = waybar
exec-once = hyprpaper
exec-once = systemctl --user start plasma-polkit-agent

# Default apps
$terminal = kitty
$fileManager = $terminal yazi

# Winrules
windowrulev2 = pin, class: Rofi
windowrulev2 = stayfocused, class:^(Rofi)$
windowrulev2 = float, class:^(Rofi)$

# Window management
bind = SUPER, F, fullscreen,
bind = SUPER, V, togglefloating,
bind = SUPER, Q, killactive,
bind = SUPER, W, togglesplit,

# Launching
bind = SUPER, SPACE, exec, $terminal
bind = SUPER, E, exec, $fileManager

# Bar shortcuts
bind = SUPER, A, exec, applauncher
bind = SUPER, S, exec, powermenu
bind = SUPER, D, exec, screenshot
bind = SUPER, Z, exec, wifimenu

# Refreshing
bind = SUPER, P, exec, killall waybar
bind = SUPER, P, exec, killall hyprpaper
bind = SUPER, P, exec, waybar
bind = SUPER, P, exec, hyprpaper

# Scary!
bind = SUPER, O, exit,

# Moving through windows
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER CTRL, right, workspace, +1
bind = SUPER CTRL, left, workspace, -1

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d
bind = SUPER CTRL, L, workspace, +1
bind = SUPER CTRL, H, workspace, -1

# Moving windows
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d
bind = SUPER CTRL & SHIFT, right, movetoworkspace, +1
bind = SUPER CTRL & SHIFT, left, movetoworkspace, -1
bindm = SUPER, mouse:272, movewindow
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER CTRL & SHIFT, L, movetoworkspace, +1
bind = SUPER CTRL & SHIFT, H, movetoworkspace, -1

# Moving & resizing windows
bind = SUPER ALT, left, resizeactive, -20 0 0 0
bind = SUPER ALT, right, resizeactive, 20 0 0 0
bind = SUPER ALT, up, resizeactive, 0 -20 0 0
bind = SUPER ALT, down, resizeactive, 0 20 0 0
bind = SUPER ALT & CTRL, left, resizeactive, 0 0 -20 0 0
bind = SUPER ALT & CTRL, right, resizeactive, 0 0 20 0
bind = SUPER ALT & CTRL, up, resizeactive, 0 0 0 -20
bind = SUPER ALT & CTRL, down, resizeactive, 0 0 0 20
bindm = SUPER, mouse:273, resizewindow
bind = SUPER ALT, H, resizeactive, -20 0 0 0
bind = SUPER ALT, L, resizeactive, 20 0 0 0
bind = SUPER ALT, K, resizeactive, 0 -20 0 0
bind = SUPER ALT, J, resizeactive, 0 20 0 0
bind = SUPER ALT & CTRL, L, resizeactive, 0 0 -20 0 0
bind = SUPER ALT & CTRL, H, resizeactive, 0 0 20 0
bind = SUPER ALT & CTRL, K, resizeactive, 0 0 0 -20
bind = SUPER ALT & CTRL, J, resizeactive, 0 0 0 20
