# This file focues on visual settings

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

windowrulev2 = rounding 0, class: Rofi
windowrulev2 = opacity 2, class: librewolf-default

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 5
    
    col.active_border = rgba(ffffffff)
    col.inactive_border = rgba(77777777)

    layout = master
}

decoration {
    rounding = 0

	drop_shadow = false
	
	fullscreen_opacity = 1
    inactive_opacity = 0.9
    active_opacity = 0.9
}

decoration:blur {
	size = 12
	noise = 0
}

animations {
	bezier = zero, 0, 0, 0, 0

	animation = global, 1, 7, default
    animation = border, 1, 15, default
    animation = windowsOut, 1, 5, zero
}

misc{
	disable_splash_rendering = true
	disable_hyprland_logo = true
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_is_master = false
    mfact = 0.5
}
